### ISSUE TITLE
[Suggestion] lang

### ISSUE THREAD

**Issue by Shad0wB1ade** [ShenTengTu/LargeSign#1]
This is a really cool mod and I like it.

Don't make the text in the menu hardcoded make it so that you use lang files so that there could be language localizations for this mod.
I want to help with greek and russian localizations ;)

**Comment by ShenTengTu** [comment]
Thank you for your suggestion.I will research on how to use lang files and consider modifying the code.

**Comment by ShenTengTu** [comment]
I update the code and you can localize now.(go to see lang floder)

**Comment by Shad0wB1ade** [comment]
Ok I will work on this tomorrow (Sunday), I don't have time today. Thanks for the update! ;)
