### ISSUE TITLE
Compatibility for other mod

### ISSUE THREAD

**Issue by ShenTengTu** [ShenTengTu/LargeSign#3]
Some player report the error about the Compatibility for other mod(e.g. Ars Magica 2).I found the same problem as belaow:

According to error log,the problem function in other mod is:

   public void func_150895_a(Item p_150895_1_, CreativeTabs p_150895_2_, List p_150895_3_) {
      this.field_150939_a.func_149666_a(p_150895_1_, p_150895_2_, p_150895_3_);
   }

then in this mod is:

```
public void getSubItems(Item p_150895_1_, CreativeTabs p_150895_2_, List p_150895_3_)
{
    p_150895_3_.add(new ItemStack(p_150895_1_, 1, 0));
}
```

and throw java.lang.NullPointerException: Initializing game .

**Comment by ghost** [comment]
Use the Large Sign1.1, and Forge1232, this problem has been settled.
